# route:
#   group_by: ['alertname']
#   group_wait: 30s # How long to initailly wait for other alerts to send notifications to group . Def:30s
#   group_interval: 5m # comes into play when 1st alert is already send out.Instruct alert mgr to wait for sometime to see if there are more alerts before sending subsequent alerts
#   repeat_interval: 1h
#   receiver: 'web.hook'
# receivers:
#   - name: 'web.hook'
#     webhook_configs:
#       - url: 'http://127.0.0.1:5001/'
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']

global:
  smtp_from: 'abc@gmail.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'abc@gmail.com'
  smtp_auth_identity: 'abc@gmail.com'
  smtp_auth_password: 'jajdsaldhasd'


route:
  receiver: admin

  routes:
    - match: 
        team: TeamC
      # Fallback receiver  
      receiver: team-c
      routes:
        - match: 
            severity: Critical
          receiver: team-c-manager

receivers:
  - name: admin
    email_configs:
     - to: 'target@gmail.com'
       

  - name: team-c
    email_configs:
     - to: 'target@gmail.com'
       
  - name: team-c-manager
    email_configs:
     - to: 'target2@gmail.com'
       
