global:
  scrape_interval: 10s
  # scrape_timeout: 10s
  evaluation_interval: 10s

rule_files:
  - prometheus-rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'host.docker.internal:9093' ]

scrape_configs:
  
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
        
  - job_name: apollo
    metrics_path: /metrics
    scheme: http
    file_sd_configs:
      - files:
          - file_sd.json
 
      
  - job_name: blackbox_exporter
    static_configs:
      - targets: ['host.docker.internal:9115']
        

# Try to hit http://localhost:9115/probe?module=http_2xx&target=host.docker.internal:5000&debug=true

# If we don't add relabel configs it will try to scrape http://host.docker.internal:5000/probe

  - job_name: probe-node-app
    scrape_interval: 30s
    static_configs:
       - targets:
           - 'host.docker.internal:5000/health-check'
           - 'host.docker.internal:5001/health-check'
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
    #  - source_labels: [__address__]
    #    target_label: __address__
    #    regex: (.*)
    #    replacement: '${1}/health-check'
     - source_labels: [__address__] # Here we need to replace address of target i.e host.docker.internal:5000 to address of blackbox exporter
       target_label: __param_target # temp assignment to __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: host.docker.internal:9115 
        